version: '3.5'
services:
  dev:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes: 
      - .:/var/www/gateway
      - /var/www/gateway/node_modules
    restart: always
    hostname: maps
    env_file:
      - .env
    networks:
      - backend

  maps-prod:
    build: .
    volumes: 
      - .:/var/www/gateway
      - /var/www/gateway/node_modules
    restart: always
    hostname: maps
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network